apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 8089
  ingressClassName: tailscale
  tls:
  - hosts:
    - nginx
