apiVersion: v2
name: tailscale-operator
description: Tailscale Kubernetes Operator
type: application
version: 0.1.0
appVersion: "1.88.2"

dependencies:
  - name: tailscale-operator
    condition: tailscale-operator.enabled
    repository: https://pkgs.tailscale.com/helmcharts
    version: 1.88.2
